### ISSUE TITLE
Reporte Practica2

### ISSUE THREAD

**Issue by Yeim1129** [SistemasTecTlaxiaco/practica-de-visual-studio-Yeim1129#2]
[Hernandez_Arroyo_J Manuel_Reporte de practica2.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-Yeim1129/files/6190983/Hernandez_Arroyo_J.Manuel_Reporte.de.practica2.pdf)

**Comment by josealfredo79** [comment]
Esta practica no tiene objetivo

**Comment by josealfredo79** [comment]
La calificacion debe ser escrita por aca.

**Comment by josealfredo79** [comment]
No tiene indice de figuras, ni resultados
